ingress:
  enabled: false

service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"

serviceAccount:
  name: atlantis
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::749942219478:role/atlantis-ops-role

image:
  repository: quay.io/procoredevops/atlantis-helm-chart
  tag: procore-atlantis-v0.17.0-0.0.2
  pullPolicy: IfNotPresent

imagePullSecrets:
  - procoredevops-procore-sherpa-pull-secret

resources:
  requests:
    memory: 2Gi
    cpu: 1
  limits:
    memory: 2Gi
    cpu: 1

repoConfig: |
 ---
 repos:
 - id: /.*/
   workflow: workflow
   apply_requirements: [approved]
 workflows:
   workflow:
     plan:
       steps:
       - run: terraform${"${ATLANTIS_TERRAFORM_VERSION}"} init -input=false -no-color
       - run: terraform${"${ATLANTIS_TERRAFORM_VERSION}"} plan -input=false -refresh -no-color -out $PLANFILE | tfmask
     apply:
       steps:
       - run: terraform${"${ATLANTIS_TERRAFORM_VERSION}"} apply -no-color $PLANFILE | tfmask
     justtesting:
       steps:
       - run: $ATLANTIS_TERRAFORM_VERSION | whoami



## ---- BEGIN TEMPORARY SETUP CREDS SECTION ----
## Uncomment the following section for initial setup of the GitHub App.
## https://www.runatlantis.io/docs/access-credentials.html#generating-an-access-token
## Comment it again after you've registered the app with GitHub and are ready to install the secrets.
# github:
#   user: fake
#   token: fake

# environment:
#   ATLANTIS_ATLANTIS_URL: http://atlantis.production.procoretech.com/
#   ATLANTIS_GH_ORG: procore
## ---- END TEMPORARY SETUP CREDS SECTION ----


## ---- BEGIN PERMANENT SETUP CREDS SECTION ----
## Uncomment this section after the initial setup of the GitHub App.
## Configure the secrets you got when installing the app.
## Set the app-id below.

environmentSecrets:
  - name: ATLANTIS_GH_WEBHOOK_SECRET
    secretKeyRef:
      name: atlantis-secret
      key: github_secret

environment:
  ATLANTIS_GH_APP_ID: 114426
  ATLANTIS_GH_APP_KEY_FILE: /atlantis_keys/gh_app_key_file.pem
  ATLANTIS_WRITE_GIT_CREDS: true
  ATLANTIS_ATLANTIS_URL: http://atlantis.production.procoretech.com/
  ATLANTIS_LOG_LEVEL: debug
  ATLANTIS_GH_ORG: procore
  ATLANTIS_SILENCE_ALLOWLIST_ERRORS: true
  AWS_DEFAULT_REGION: us-east-1

github: null

extraVolumes:
  - name: gh-app-key-file
    secret:
      secretName: atlantis-secret
      items:
        - key: github_key_file
          path: gh_app_key_file.pem

extraVolumeMounts:
  - mountPath: /atlantis_keys/
    name: gh-app-key-file

## ---- END PERMANENT SETUP CREDS SECTION ----
